"""Service exports for the Textual scaffold app."""

from .draft_logic import (
    DraftValidation,
    add_stream,
    build_spec,
    delete_stream,
    driver_selection_reason,
    duplicate_stream,
    move_stream_down,
    move_stream_up,
    recommended_driver_kind,
    select_stream,
    set_data_arrival,
    set_dependencies_text,
    set_device_id,
    set_display_name,
    set_driver_kind,
    set_plugin_name,
    set_preview_tab,
    set_providers_text,
    set_stream_field,
    validate_draft,
    visible_stream_fields,
)
from .output import GenerationDetails, describe_generation, project_exists
from .preview import PreviewBundle, build_preview_bundle

__all__ = [
    "DraftValidation",
    "GenerationDetails",
    "PreviewBundle",
    "add_stream",
    "build_preview_bundle",
    "build_spec",
    "delete_stream",
    "describe_generation",
    "driver_selection_reason",
    "duplicate_stream",
    "move_stream_down",
    "move_stream_up",
    "project_exists",
    "recommended_driver_kind",
    "select_stream",
    "set_data_arrival",
    "set_dependencies_text",
    "set_device_id",
    "set_display_name",
    "set_driver_kind",
    "set_plugin_name",
    "set_preview_tab",
    "set_providers_text",
    "set_stream_field",
    "validate_draft",
    "visible_stream_fields",
]
